### ISSUE TITLE
Crashes World with latest ZAWA (1.5.5)

### ISSUE THREAD

**Issue by Graywaren** [Mnesikos/LilCritters#12]
Seems like this mod is crashing minecraft when I install the latest ZAWA update. Hopefully is a simple fix cause I'd like to update ZAWA since it possibly fixes an egg problem of theirs (man I wish they'd fix spawning, but I digress...). Seems like it has something to do with the squirrel.

Here's the log:
https://pastebin.com/z9gAhKyv

Here's the crash log:
https://pastebin.com/B4EVigdt

**Comment by Mnesikos** [comment]
Working on getting the update out tonight! Thanks for reporting <3

**Comment by Mnesikos** [comment]
Done!
