### ISSUE TITLE
Ticking World

### ISSUE THREAD

**Issue by RodrigoTaipe93** [Mnesikos/LilCritters#14]
Seems like the issue still persists:

- https://paste.ee/p/5sVws

- https://paste.dimdev.org/mifanuwovu.mccrash
[Latest Log.log](https://github.com/Mnesikos/LilCritters/files/3102431/Latest.Log.log)

**Comment by JoelZBub** [comment]
There is absolutely nothing in your crash log that points to this mod.

**Comment by Mnesikos** [comment]
Exactly what Joel said.
