### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by kristinmanthoy** [Mnesikos/LilCritters#17]
i keep gettig this error message annd i  dont know how to fix it.
![Screenshot (10)](https://user-images.githubusercontent.com/62487261/77238157-47b3dd80-6ba4-11ea-8599-7a62989ee9b1.png)

**Comment by kristinmanthoy** [comment]
this is what my mods folder looks like
![Screenshot (11)](https://user-images.githubusercontent.com/62487261/77238197-8d70a600-6ba4-11ea-90ad-44e014c58093.png)

**Comment by JoelZBub** [comment]
Lil Critters has not updated to be compatible with ZAWA 2.0 yet. 
Wait for an update or downgrade zawa and bookworm to 1.7.0

**Comment by kristinmanthoy** [comment]
i downgraded versions  but now im having trouble with natural fauna mod not installing anythig older than 1.15.1

**Comment by Mnesikos** [comment]
Wait until LC updates. I'll have it out soon.
