### ISSUE TITLE
ZAWA

### ISSUE THREAD

**Issue by jawzoblivion** [Mnesikos/LilCritters#18]
not compatible with the new ZAWA version, update pls

**Comment by JoelZBub** [comment]
Just stop

**Comment by CodaBear1552** [comment]
Of course it's not compatible, ZAWA changed like everything, addon-wise. It's been like 3 days, have patience.

**Comment by 0SoggyMustache0** [comment]
Donate to the dev maybe it'll make the update come faster https://ko-fi.com/mnesikos

**Comment by Mnesikos** [comment]
Enough was said about this. I'm closing it.
