### ISSUE TITLE
(Bug) Baby Raccoons sleep with their eyes open

### ISSUE THREAD

**Issue by VakyPanda** [Mnesikos/LilCritters#20]
Baby Raccoons seem to have a sleeping issue where their eyes open when they are sleeping, i assume that they should have a blinking texture but it doesn't seem to be implemented

**Comment by Mnesikos** [comment]
They use the same as the adults... not sure why it wouldn't work? Is this a constant occurrence with absolutely no blinking for babies, or does it only happen sometimes (maybe at night?)?

**Comment by VakyPanda** [comment]
The time doesn't affect it and no matter what time you spawn it if its in the sleeping pose it has its eyes open

**Comment by Mnesikos** [comment]
Closing this old issue as it pertains to 1.12.2 and it no longer supported <3
