### ISSUE TITLE
Squirrel held food not stored

### ISSUE THREAD

**Issue by 0SoggyMustache0** [Mnesikos/LilCritters#3]
The heldFood variable in EntityTreeSquirrel does not store the item NBT data in the squirrels NBT data.

**Comment by Mnesikos** [comment]
Reasoning: "They only eat it for a second or two, so if you're hopping off your world right after you give a squirrel an acorn, it doesn't really matter. The squirrel gains food from it the second you give it to them anyways."

**Comment by 0SoggyMustache0** [comment]
Even if the squirrel only uses the information for a little bit it should still be stored so that the network sync can occur more affectively.
