### ISSUE TITLE
[request] configurable drop rate/toggle for acorns from tree leaves

### ISSUE THREAD

**Issue by xkforce** [Mnesikos/LilCritters#9]
Would it be possible to be able to adjust the drop rateor toggle the drop on/off for acorns from tree leaves?  Ideally I'd like the acorn oak tree from binnie's mods be the source of acorns (which the squirrels do appear to eat just like the ones added from lil critters) and oak trees just drop saplings and apples.  But for some reason, dropt isn't able to modify the acorn drops to do this.

**Comment by Mnesikos** [comment]
Yes, thank you so much for requesting this! I had every intention to make them toggleable, but have completely forgotten.

Expect this in the next update for sure.

**Comment by xkforce** [comment]
Excellent.  Keep up the good work.

**Comment by Mnesikos** [comment]
Done!
